services:
  db:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: word_flow

  admin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    links:
      - db:mysql
    depends_on:
      - db
    ports:
      - 8080:80

  backend:
    build: .
    image: node:19.3.0
    container_name: backend
    working_dir: /usr/src/app
    restart: always
    links:
      - db:mysql
    depends_on:
      - db
    ports:
      - 80:3000
