services:
  db:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: word_flow

  admin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    links:
      - db:mysql
    depends_on:
      - db
    ports:
      - 8080:80

  backend:
    build: ./backend
    image: node:19.3.0
    container_name: backend
    working_dir: /usr/src/app
    restart: always
    links:
      - db:mysql
    depends_on:
      - db
    ports:
      - 80:3000
    extra_hosts:
      # using Docker Compose + Linux, have to add extra_hosts on docker-compose.yaml file (at least for now)
      # https://stackoverflow.com/questions/48546124/what-is-linux-equivalent-of-host-docker-internal/67158212#67158212
      # https://github.com/docker/for-linux/issues/264#issuecomment-784985736
      - "host.docker.internal:host-gateway"
