- id: redeploy
  execute-command: ./deploy.sh
  command-working-directory: ./
  response-message: Redeploying started
  trigger-rule:
    and:
      - match:
          type: payload-hash-sha1
          secret: ${WEBHOOK_SECRET}
          parameter:
            source: header
            name: X-Hub-Signature
      - match:
          type: value
          value: refs/heads/main
          parameter:
            source: payload
            name: ref
